name: Release Docker Image

on:
  workflow_dispatch: # for manual testing
  push:
    # Publish semver tags as releases:
    tags: ["v*.*.*"]

jobs:
  call-docker-release:
    permissions:
      contents: read
      packages: write
    uses: thealtoclef/modular-automations/.github/workflows/docker-release.yaml@main
    with:
      dockerfile_path: docker/Dockerfile
